source :rubygems

gem 'erubis', '>= 2.7.0'
gem 'exec_sandbox', '>= 0.1.1'
gem 'hashie', '>= 1.2.0'
gem 'highline', '>= 1.6.2'
gem 'json', '>= 1.6.1'
gem 'rake', '>= 0.9.2'
gem 'ruby-debug19', '>= 0.11.6'
gem 'stellar', '>= 0.2.0'
